from datetime import datetime, timedelta
from typing import Any, Generator, Union

AnonUserDict = dict[str, int]
UserDict = dict[str, Union[str, int, datetime, None]]
TaskDict = dict[str, Union[str, int, timedelta, bool]]
DaylistDict = dict[str, Union[int, datetime, list[TaskDict]]]

class DBQueriesWrapper:
    """Wrapper for dynamically imported SQL functions - typing and autocomplete."""

    def transaction(self) -> Any: ...

    # Users
    # read
    @staticmethod
    def count_users(user_id: int) -> int: ...
    @staticmethod
    def count_anon_users() -> int: ...
    @staticmethod
    def count_registered_users() -> int: ...
    @staticmethod
    def get_user(id: int) -> UserDict | None: ...
    @staticmethod
    def get_registered_user(email: str) -> UserDict | None: ...
    @staticmethod
    def get_anon_user() -> AnonUserDict | None: ...
    # create
    @staticmethod
    def add_anon_user() -> int: ...
    @staticmethod
    def add_registered_user(email: str, password_hash: str) -> int: ...
    # update
    @staticmethod
    def register_anon_user(id: int, email: str, password_hash: str) -> int: ...
    # delete
    @staticmethod
    def delete_user(id: int) -> int: ...
    @staticmethod
    def delete_all_users() -> int: ...

    # Daylists
    @staticmethod
    def get_active_daylist(user_id: int) -> DaylistDict | None: ...
    @staticmethod
    def add_daylist(user_id: int, expiry: Union[str, datetime]) -> int: ...

    # Tasks
    # read
    @staticmethod
    def count_tasks(daylist_id: int) -> int: ...
    @staticmethod
    def get_task(id: int) -> TaskDict | None: ...
    @staticmethod
    def get_current_tasks(user_id: int) -> Generator[TaskDict, None, None]: ...
    @staticmethod
    def get_pending_tasks(user_id: int) -> Generator[TaskDict, None, None]: ...
    @staticmethod
    def get_done_tasks(user_id: int) -> Generator[TaskDict, None, None]: ...
    # create
    @staticmethod
    def add_task_for_user(user_id: int, title: str, estimate: timedelta) -> int: ...
    @staticmethod
    def add_task_to_list(daylist_id: int, title: str, estimate: timedelta) -> int: ...
    # update
    @staticmethod
    def complete_task(id: int) -> int: ...
    @staticmethod
    def uncomplete_task(id: int) -> int: ...
    # delete
    @staticmethod
    def delete_task(id: int) -> int: ...

def query_connect(url: str) -> DBQueriesWrapper: ...
